### ISSUE TITLE
Last minute favicon markbot help

### ISSUE THREAD

**Issue by sent0007** [sent0007/web-design-2-independent-project#1]
Markbot is giving me this message below and I am completely stumped.

<img width="887" alt="Screen Shot 2020-12-18 at 11 06 26 PM" src="https://user-images.githubusercontent.com/55108791/102680435-20fff300-4186-11eb-8ded-d654bbe9f42d.png">

Any ideas ? Sorry for the late issue :confused:

@hellachella
@JessJodoin
@MacKenzieRose
@HannahDelaney

**Comment by MacKenzieRose** [comment]
These errors come from the content in this lesson:

https://learn-the-web.algonquindesign.ca/courses/web-dev-3/micro-interface-branding/

Let me know if you need any help following along with it :)

**Comment by sent0007** [comment]
Thanks I will let you know and a massive thanks for the quick reply and all the help this semester!
